# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pyFROG_gui.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
import pyqtgraph as pg

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1200, 865)
        MainWindow.setMaximumSize(QtCore.QSize(1200, 16777215))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.plt_trace = pg.ImageView(self.centralwidget)
        self.plt_trace.setGeometry(QtCore.QRect(680, 30, 500, 500))
        self.plt_trace.setObjectName("plt_trace")
        self.plt_spectrum = pg.PlotWidget(self.centralwidget)
        self.plt_spectrum.setGeometry(QtCore.QRect(30, 30, 500, 350))
        self.plt_spectrum.setObjectName("plt_spectrum")
        self.plt_specac = pg.PlotWidget(self.centralwidget)
        self.plt_specac.setGeometry(QtCore.QRect(570, 30, 100, 500))
        self.plt_specac.setObjectName("plt_specac")
        self.plt_ac = pg.PlotWidget(self.centralwidget)
        self.plt_ac.setGeometry(QtCore.QRect(680, 540, 500, 151))
        self.plt_ac.setObjectName("plt_ac")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(10, 400, 311, 219))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.in_boxcar = QtWidgets.QSpinBox(self.horizontalLayoutWidget_2)
        self.in_boxcar.setObjectName("in_boxcar")
        self.gridLayout_4.addWidget(self.in_boxcar, 1, 1, 1, 1)
        self.in_specexposure = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        self.in_specexposure.setObjectName("in_specexposure")
        self.gridLayout_4.addWidget(self.in_specexposure, 0, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_5.setObjectName("label_5")
        self.gridLayout_4.addWidget(self.label_5, 0, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_8.setObjectName("label_8")
        self.gridLayout_4.addWidget(self.label_8, 2, 0, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_16.setObjectName("label_16")
        self.gridLayout_4.addWidget(self.label_16, 5, 0, 1, 1)
        self.c_calibration = QtWidgets.QCheckBox(self.horizontalLayoutWidget_2)
        self.c_calibration.setObjectName("c_calibration")
        self.gridLayout_4.addWidget(self.c_calibration, 7, 0, 1, 1)
        self.c_darkcounts = QtWidgets.QCheckBox(self.horizontalLayoutWidget_2)
        self.c_darkcounts.setObjectName("c_darkcounts")
        self.gridLayout_4.addWidget(self.c_darkcounts, 7, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_3.setObjectName("label_3")
        self.gridLayout_4.addWidget(self.label_3, 6, 0, 1, 1)
        self.c_subbkg = QtWidgets.QCheckBox(self.horizontalLayoutWidget_2)
        self.c_subbkg.setObjectName("c_subbkg")
        self.gridLayout_4.addWidget(self.c_subbkg, 8, 0, 1, 1)
        self.in_numberaverage = QtWidgets.QSpinBox(self.horizontalLayoutWidget_2)
        self.in_numberaverage.setObjectName("in_numberaverage")
        self.gridLayout_4.addWidget(self.in_numberaverage, 3, 1, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_15.setObjectName("label_15")
        self.gridLayout_4.addWidget(self.label_15, 4, 0, 1, 1)
        self.in_specbasename = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        self.in_specbasename.setObjectName("in_specbasename")
        self.gridLayout_4.addWidget(self.in_specbasename, 5, 1, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_14.setObjectName("label_14")
        self.gridLayout_4.addWidget(self.label_14, 3, 0, 1, 1)
        self.in_percentnoise = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        self.in_percentnoise.setObjectName("in_percentnoise")
        self.gridLayout_4.addWidget(self.in_percentnoise, 2, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_6.setObjectName("label_6")
        self.gridLayout_4.addWidget(self.label_6, 1, 0, 1, 1)
        self.in_specsavedir = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        self.in_specsavedir.setObjectName("in_specsavedir")
        self.gridLayout_4.addWidget(self.in_specsavedir, 4, 1, 1, 1)
        self.horizontalLayout_2.addLayout(self.gridLayout_4)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.p_loadspec = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.p_loadspec.setObjectName("p_loadspec")
        self.verticalLayout_4.addWidget(self.p_loadspec)
        self.p_loadbkg = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.p_loadbkg.setObjectName("p_loadbkg")
        self.verticalLayout_4.addWidget(self.p_loadbkg)
        self.p_savespec = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.p_savespec.setObjectName("p_savespec")
        self.verticalLayout_4.addWidget(self.p_savespec)
        self.p_takebkg = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.p_takebkg.setObjectName("p_takebkg")
        self.verticalLayout_4.addWidget(self.p_takebkg)
        self.pushButton_8 = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.pushButton_8.setObjectName("pushButton_8")
        self.verticalLayout_4.addWidget(self.pushButton_8)
        self.horizontalLayout_2.addLayout(self.verticalLayout_4)
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 590, 566, 231))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.p_actenable = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.p_actenable.setObjectName("p_actenable")
        self.gridLayout_2.addWidget(self.p_actenable, 3, 1, 1, 1)
        self.p_acthome = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.p_acthome.setObjectName("p_acthome")
        self.gridLayout_2.addWidget(self.p_acthome, 3, 0, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_12.setObjectName("label_12")
        self.gridLayout_2.addWidget(self.label_12, 2, 0, 1, 1)
        self.in_actstatus = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.in_actstatus.setText("")
        self.in_actstatus.setObjectName("in_actstatus")
        self.gridLayout_2.addWidget(self.in_actstatus, 2, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_11.setObjectName("label_11")
        self.gridLayout_2.addWidget(self.label_11, 1, 0, 1, 1)
        self.in_actip = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.in_actip.setObjectName("in_actip")
        self.gridLayout_2.addWidget(self.in_actip, 1, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 0, 0, 1, 1)
        self.p_actinit = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.p_actinit.setObjectName("p_actinit")
        self.gridLayout_2.addWidget(self.p_actinit, 4, 0, 1, 1)
        self.in_groupname = QtWidgets.QComboBox(self.horizontalLayoutWidget)
        self.in_groupname.setObjectName("in_groupname")
        self.in_groupname.addItem("")
        self.gridLayout_2.addWidget(self.in_groupname, 0, 1, 1, 1)
        self.p_actsetlim = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.p_actsetlim.setObjectName("p_actsetlim")
        self.gridLayout_2.addWidget(self.p_actsetlim, 5, 0, 1, 1)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.p_actsaveposition = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.p_actsaveposition.setObjectName("p_actsaveposition")
        self.horizontalLayout_7.addWidget(self.p_actsaveposition)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_24 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_24.setObjectName("label_24")
        self.verticalLayout_2.addWidget(self.label_24)
        self.out_saveposition = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.out_saveposition.setObjectName("out_saveposition")
        self.verticalLayout_2.addWidget(self.out_saveposition)
        self.horizontalLayout_7.addLayout(self.verticalLayout_2)
        self.gridLayout_2.addLayout(self.horizontalLayout_7, 4, 1, 1, 1)
        self.gridLayout_7 = QtWidgets.QGridLayout()
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.label_22 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_22.setObjectName("label_22")
        self.gridLayout_7.addWidget(self.label_22, 0, 0, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_23.setObjectName("label_23")
        self.gridLayout_7.addWidget(self.label_23, 0, 1, 1, 1)
        self.in_actminlim = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.in_actminlim.setObjectName("in_actminlim")
        self.gridLayout_7.addWidget(self.in_actminlim, 1, 0, 1, 1)
        self.in_actmaxlim = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.in_actmaxlim.setObjectName("in_actmaxlim")
        self.gridLayout_7.addWidget(self.in_actmaxlim, 1, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout_7, 5, 1, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout_2)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_4 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 1, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 2, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 5, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 4, 0, 1, 1)
        self.in_actlargerel = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.in_actlargerel.setObjectName("in_actlargerel")
        self.gridLayout.addWidget(self.in_actlargerel, 5, 1, 1, 1)
        self.p_actsmallback = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.p_actsmallback.setObjectName("p_actsmallback")
        self.gridLayout.addWidget(self.p_actsmallback, 4, 2, 1, 1)
        self.p_actlargeforward = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.p_actlargeforward.setObjectName("p_actlargeforward")
        self.gridLayout.addWidget(self.p_actlargeforward, 5, 3, 1, 1)
        self.p_actsmallforward = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.p_actsmallforward.setObjectName("p_actsmallforward")
        self.gridLayout.addWidget(self.p_actsmallforward, 4, 3, 1, 1)
        self.in_actsmallrel = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.in_actsmallrel.setObjectName("in_actsmallrel")
        self.gridLayout.addWidget(self.in_actsmallrel, 4, 1, 1, 1)
        self.p_actlargeback = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.p_actlargeback.setObjectName("p_actlargeback")
        self.gridLayout.addWidget(self.p_actlargeback, 5, 2, 1, 1)
        self.in_actabsmove = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.in_actabsmove.setObjectName("in_actabsmove")
        self.gridLayout.addWidget(self.in_actabsmove, 2, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 1, 2, 1, 1)
        self.p_actabsmove = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.p_actabsmove.setObjectName("p_actabsmove")
        self.gridLayout.addWidget(self.p_actabsmove, 2, 2, 1, 1)
        self.out_actcurrentpos = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.out_actcurrentpos.setReadOnly(False)
        self.out_actcurrentpos.setObjectName("out_actcurrentpos")
        self.gridLayout.addWidget(self.out_actcurrentpos, 1, 3, 1, 1)
        self.c_actenableabs = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        self.c_actenableabs.setObjectName("c_actenableabs")
        self.gridLayout.addWidget(self.c_actenableabs, 2, 3, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout)
        self.STOP = QtWidgets.QPushButton(self.centralwidget)
        self.STOP.setGeometry(QtCore.QRect(1110, 0, 75, 23))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.STOP.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.STOP.setFont(font)
        self.STOP.setObjectName("STOP")
        #self.flameWidget = FlameWidget(self.centralwidget)
        #self.flameWidget.setGeometry(QtCore.QRect(40, 40, 481, 331))
        #self.flameWidget.setObjectName("flameWidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(610, 710, 577, 110))
        self.widget.setObjectName("widget")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_17 = QtWidgets.QLabel(self.widget)
        self.label_17.setObjectName("label_17")
        self.gridLayout_3.addWidget(self.label_17, 1, 0, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.widget)
        self.label_18.setObjectName("label_18")
        self.gridLayout_3.addWidget(self.label_18, 1, 1, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.widget)
        self.label_19.setObjectName("label_19")
        self.gridLayout_3.addWidget(self.label_19, 1, 2, 1, 1)
        self.in_scanstepsize = QtWidgets.QLineEdit(self.widget)
        self.in_scanstepsize.setObjectName("in_scanstepsize")
        self.gridLayout_3.addWidget(self.in_scanstepsize, 2, 1, 1, 1)
        self.in_scanlen = QtWidgets.QLineEdit(self.widget)
        self.in_scanlen.setObjectName("in_scanlen")
        self.gridLayout_3.addWidget(self.in_scanlen, 2, 0, 1, 1)
        self.in_scanstepnumbers = QtWidgets.QLineEdit(self.widget)
        self.in_scanstepnumbers.setObjectName("in_scanstepnumbers")
        self.gridLayout_3.addWidget(self.in_scanstepnumbers, 2, 2, 1, 1)
        self.horizontalLayout_3.addLayout(self.gridLayout_3)
        self.horizontalLayout_4.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_5.addLayout(self.horizontalLayout_4)
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.p_aquirescan = QtWidgets.QPushButton(self.widget)
        self.p_aquirescan.setObjectName("p_aquirescan")
        self.gridLayout_6.addWidget(self.p_aquirescan, 0, 0, 1, 1)
        self.p_bkgscan = QtWidgets.QPushButton(self.widget)
        self.p_bkgscan.setObjectName("p_bkgscan")
        self.gridLayout_6.addWidget(self.p_bkgscan, 3, 0, 1, 1)
        self.p_savescan = QtWidgets.QPushButton(self.widget)
        self.p_savescan.setObjectName("p_savescan")
        self.gridLayout_6.addWidget(self.p_savescan, 2, 0, 1, 1)
        self.c_scanautosave = QtWidgets.QCheckBox(self.widget)
        self.c_scanautosave.setObjectName("c_scanautosave")
        self.gridLayout_6.addWidget(self.c_scanautosave, 1, 0, 1, 1)
        self.horizontalLayout_5.addLayout(self.gridLayout_6)
        self.horizontalLayout_6.addLayout(self.horizontalLayout_5)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_20 = QtWidgets.QLabel(self.widget)
        self.label_20.setObjectName("label_20")
        self.verticalLayout.addWidget(self.label_20)
        self.in_scansavedir = QtWidgets.QLineEdit(self.widget)
        self.in_scansavedir.setMinimumSize(QtCore.QSize(200, 20))
        self.in_scansavedir.setObjectName("in_scansavedir")
        self.verticalLayout.addWidget(self.in_scansavedir)
        self.label_21 = QtWidgets.QLabel(self.widget)
        self.label_21.setObjectName("label_21")
        self.verticalLayout.addWidget(self.label_21)
        self.in_tracebasename = QtWidgets.QLineEdit(self.widget)
        self.in_tracebasename.setObjectName("in_tracebasename")
        self.verticalLayout.addWidget(self.in_tracebasename)
        self.horizontalLayout_6.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1200, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.in_specexposure.setText(_translate("MainWindow", "100.0"))
        self.label_5.setText(_translate("MainWindow", "Flame Exposure Time"))
        self.label_8.setText(_translate("MainWindow", "Percent Noise Cutoff"))
        self.label_16.setText(_translate("MainWindow", "Base Name"))
        self.c_calibration.setText(_translate("MainWindow", "Calibration"))
        self.c_darkcounts.setText(_translate("MainWindow", "Dark Counts"))
        self.label_3.setText(_translate("MainWindow", "Flame Settings"))
        self.c_subbkg.setText(_translate("MainWindow", "Subtract Bkg"))
        self.label_15.setText(_translate("MainWindow", "Save Directory"))
        self.in_specbasename.setText(_translate("MainWindow", "frog_trace"))
        self.label_14.setText(_translate("MainWindow", "Spectra Saved"))
        self.in_percentnoise.setText(_translate("MainWindow", "0.0"))
        self.label_6.setText(_translate("MainWindow", "Flame Box Car Averaging"))
        self.in_specsavedir.setText(_translate("MainWindow", "C:\\Users\\Sorry\\Documents\\data\\FROG Traces"))
        self.p_loadspec.setText(_translate("MainWindow", "Load Spectrum"))
        self.p_loadbkg.setText(_translate("MainWindow", "Load Background"))
        self.p_savespec.setText(_translate("MainWindow", "Save Spectrum"))
        self.p_takebkg.setText(_translate("MainWindow", "Take Background"))
        self.pushButton_8.setText(_translate("MainWindow", "PushButton"))
        self.p_actenable.setText(_translate("MainWindow", "Enable/Disable"))
        self.p_acthome.setText(_translate("MainWindow", "Home"))
        self.label_12.setText(_translate("MainWindow", "Status"))
        self.label_11.setText(_translate("MainWindow", "IP Address"))
        self.in_actip.setText(_translate("MainWindow", "FROG"))
        self.label_10.setText(_translate("MainWindow", "Group Name"))
        self.p_actinit.setText(_translate("MainWindow", "Initialize"))
        self.in_groupname.setItemText(0, _translate("MainWindow", "FROG"))
        self.p_actsetlim.setText(_translate("MainWindow", "Update\n"
" Limits"))
        self.p_actsaveposition.setText(_translate("MainWindow", "Save Position"))
        self.label_24.setText(_translate("MainWindow", "Last Saved Position"))
        self.label_22.setText(_translate("MainWindow", "Lower\n"
"Limit(mm)"))
        self.label_23.setText(_translate("MainWindow", "Upper\n"
"Limit"))
        self.in_actminlim.setText(_translate("MainWindow", "0"))
        self.in_actmaxlim.setText(_translate("MainWindow", "10"))
        self.label_4.setText(_translate("MainWindow", "Stage Settings"))
        self.label.setText(_translate("MainWindow", "Absolute\n"
"Move"))
        self.label_9.setText(_translate("MainWindow", "Large\n"
"Relative\n"
"Move"))
        self.label_2.setText(_translate("MainWindow", "Small\n"
"Relative\n"
"Move"))
        self.in_actlargerel.setText(_translate("MainWindow", "0.0"))
        self.p_actsmallback.setText(_translate("MainWindow", "Small Step\n"
" Back"))
        self.p_actlargeforward.setText(_translate("MainWindow", "Large Step\n"
"Forward"))
        self.p_actsmallforward.setText(_translate("MainWindow", "Small Step\n"
"Forward"))
        self.in_actsmallrel.setText(_translate("MainWindow", "0.0"))
        self.p_actlargeback.setText(_translate("MainWindow", "Large Step\n"
"Back"))
        self.in_actabsmove.setText(_translate("MainWindow", "0.0"))
        self.label_7.setText(_translate("MainWindow", "Currrent Position:"))
        self.p_actabsmove.setText(_translate("MainWindow", "Absolute\n"
"Move"))
        self.c_actenableabs.setText(_translate("MainWindow", "Enable Abs.\n"
"Move"))
        self.STOP.setText(_translate("MainWindow", "CLOSE"))
        self.label_17.setText(_translate("MainWindow", "Scan Length (fs)"))
        self.label_18.setText(_translate("MainWindow", "Scan Step Size (fs)"))
        self.label_19.setText(_translate("MainWindow", "Number of Steps"))
        self.p_aquirescan.setText(_translate("MainWindow", "Aquire Scan"))
        self.p_bkgscan.setText(_translate("MainWindow", "Background Scan"))
        self.p_savescan.setText(_translate("MainWindow", "Save Scan"))
        self.c_scanautosave.setText(_translate("MainWindow", "Autosave"))
        self.label_20.setText(_translate("MainWindow", "Trace Directory"))
        self.label_21.setText(_translate("MainWindow", "Trace Name"))

#from Flame.FlameWidget import FlameWidget

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

