# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'daq_GUI.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(834, 790)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_4.addWidget(self.label_3)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_4.addItem(spacerItem)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 1, 0, 1, 1)
        self.numberDiagnostics = QtWidgets.QSpinBox(self.centralwidget)
        self.numberDiagnostics.setProperty("value", 1)
        self.numberDiagnostics.setObjectName("numberDiagnostics")
        self.gridLayout_2.addWidget(self.numberDiagnostics, 0, 1, 1, 1)
        self.runNumber = QtWidgets.QSpinBox(self.centralwidget)
        self.runNumber.setProperty("value", 1)
        self.runNumber.setObjectName("runNumber")
        self.gridLayout_2.addWidget(self.runNumber, 1, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.confirmSetup = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.confirmSetup.setFont(font)
        self.confirmSetup.setObjectName("confirmSetup")
        self.gridLayout_2.addWidget(self.confirmSetup, 0, 2, 1, 1)
        self.horizontalLayout_3.addLayout(self.gridLayout_2)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_2.addWidget(self.label_5)
        self.saveDir = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.saveDir.setFont(font)
        self.saveDir.setObjectName("saveDir")
        self.horizontalLayout_2.addWidget(self.saveDir)
        self.browse = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.browse.setFont(font)
        self.browse.setObjectName("browse")
        self.horizontalLayout_2.addWidget(self.browse)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_4.addItem(spacerItem1)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_4.addWidget(self.label_4)
        self.diagnosticTable = QtWidgets.QTableWidget(self.centralwidget)
        self.diagnosticTable.setRowCount(1)
        self.diagnosticTable.setColumnCount(5)
        self.diagnosticTable.setObjectName("diagnosticTable")
        item = QtWidgets.QTableWidgetItem()
        self.diagnosticTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.diagnosticTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.diagnosticTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.diagnosticTable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.diagnosticTable.setHorizontalHeaderItem(4, item)
        self.verticalLayout_4.addWidget(self.diagnosticTable)
        self.verticalLayout_2.addLayout(self.verticalLayout_4)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 834, 31))
        self.menubar.setObjectName("menubar")
        self.menuOption = QtWidgets.QMenu(self.menubar)
        self.menuOption.setObjectName("menuOption")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.saveDefaultValuesAction = QtWidgets.QAction(MainWindow)
        self.saveDefaultValuesAction.setObjectName("saveDefaultValuesAction")
        self.exitAction = QtWidgets.QAction(MainWindow)
        self.exitAction.setObjectName("exitAction")
        self.menuOption.addAction(self.saveDefaultValuesAction)
        self.menuOption.addAction(self.exitAction)
        self.menubar.addAction(self.menuOption.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_3.setText(_translate("MainWindow", "DAQ Setup Page"))
        self.label_2.setText(_translate("MainWindow", "Please Enter Run Number"))
        self.label.setText(_translate("MainWindow", "Please Enter Number of Diagnostics"))
        self.confirmSetup.setText(_translate("MainWindow", "Confirm Setup"))
        self.label_5.setText(_translate("MainWindow", "Data Save Directory"))
        self.browse.setText(_translate("MainWindow", "Browse"))
        self.label_4.setText(_translate("MainWindow", "Diagnostic Table"))
        item = self.diagnosticTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Diagnostic Name"))
        item = self.diagnosticTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "File Type"))
        item = self.diagnosticTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "File Path"))
        item = self.diagnosticTable.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Background"))
        item = self.diagnosticTable.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Shots per Save"))
        self.menuOption.setTitle(_translate("MainWindow", "Options"))
        self.saveDefaultValuesAction.setText(_translate("MainWindow", "Save Default Values"))
        self.exitAction.setText(_translate("MainWindow", "Exit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

